version: '3.6'

services:
  nginx:
    container_name: api_lumen_nginx
    image: nginx:1.15-alpine
    ports:
      - '8080:80'
    volumes:
      - ./tools/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend

  fpm:
    container_name: api_lumen_fpm
    build:
      context: ./
      dockerfile: ./tools/docker/fpm/Dockerfile
    volumes:
      - ${BASE_DIR}/lumen/:/var/www
    networks:
      - frontend
      - backend

  database:
    container_name: api_lumen_db
    image: postgres:10-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend

volumes:
  postgresql_data:

networks:
  frontend:
  backend:
